config/routes.rb
Fitberry::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  ActiveAdmin.routes(self)

  mount Resque::Server, :at => "/resque"

  resources :activities
  resources :users
  resources :teams
  resources :challanges
  resources :milestones
  resources :blogs
  resources :comments

  devise_scope :user do
    get '/logout' => 'devise/sessions#destroy'
    get '/register' => 'users#register', :as => 'register'
    get '/profile/:id' => 'users#profile', :as => 'profile'

    post '/challanges/:id/activate' => 'challanges#activate', :as => 'activate'
    post '/challanges/:id/rebase' => 'challanges#rebase', :as => 'rebase'

    post '/blogs/:id/publish/' => 'blogs#publish', :as => 'publish'
    post '/blogs/:id/upload/' => 'blogs#upload'
    post '/blogs/preview' => 'blogs#preview'

    post '/comments/:id' => 'comments#create', :as => 'create_comment'
  end

  get '/comments/:id' => 'comments#index', :as => 'comments'
  get '/comments/new/:id' => 'comments#new', :as => 'new_comment'

  get '/history/:chid' => 'activities#index', :as => 'history'
  get '/highscore/:chid' => 'activities#highscore', :as => 'highscore'
  get '/blogs/:chid/:date/:direction' => 'blogs#slide'

  get  '/members' => 'teams#users'

  root :to => 'activities#index'
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  attr_accessible :name, :latitude, :longitude, :distance, :number, :challange_id
  attr_accessor :progress

  acts_as_gmappable
  validates :distance, :presence => true

  belongs_to :challange

  def gmaps4rails_address
    self.name
  end

  def gmaps4rails_title
    "Milestone: #{self.name} (#{self.distance} km)"
  end

  def gmaps4rails_marker_picture
    {
        :picture => 'http://labs.google.com/ridefinder/images/mm_20_red.png',
        :width   => 20,
        :height  => 20,
    }
  end
end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  before_filter :check_access, :except => :show

  # GET /milestones/new
  def new
    @challange = Challange.find(params[:challange_id])
    @milestone = Milestone.new

    respond_to do |format|
      format.js
    end
  end

  # GET /milestones/1/edit
  def edit
    @milestone = Milestone.find(params[:id])

    respond_to do |format|
      format.js
    end
  end

  # POST /milestones
  def create
    @challange = Challange.find(params[:milestone][:challange_id])
    @milestone = Milestone.new(params[:milestone])
    @milestone.number = @challange.milestones.count

    respond_to do |format|
      if @milestone.save
        format.js { render action: "index" }
      else
        format.js { render action: "new" }
      end
    end
  end

  # PUT /milestones/1
  def update
    @milestone = Milestone.find(params[:id])
    @challange = @milestone.challange

    respond_to do |format|
      if @milestone.update_attributes(params[:milestone])
        format.js { render action: "index" }
      else
        format.js { render action: "edit" }
      end
    end
  end

  # DELETE /milestones/1
  def destroy
    @milestone = Milestone.find(params[:id])
    @milestone.destroy

    render :nothing => true
  end
end

app/views/milestones/_edit.html.erb
<%= semantic_form_for @milestone, :remote => true do |f| %>
  <%= f.input :name, :hint => 'Milestone name, eg. Basel' %>
  <%= f.input :latitude, :hint => 'Geo position (latitude)', :input_html => {:'data-geo' => 'lat'} %>
  <%= f.input :longitude, :hint => 'Geo position (longitude)', :input_html => {:'data-geo' => 'lng'} %>
  <%= f.input :distance, :hint => 'Distance (km) to reach this milestone, eg. 10.5' %>
  <%= f.input :number, :hint => 'to get correct milestones order' %>

  <%= f.actions do %>
      <%= f.action :submit, :label => 'Ok, now it looks good', :button_html => { :disable_with => 'Wait...' }  %>
  <% end %>
<% end %>

app/views/milestones/_index.html.erb
<% @challange.milestones.each do |milestone| %>
  <li><strong><%= milestone.distance %> km</strong>&nbsp;<%= milestone.name %> (<%= link_to 'edit', edit_milestone_path(milestone), :remote => true %> | <%= link_to 'delete', milestone, :method => :delete, :class => 'delete' %>)</li>
<% end %>

app/views/milestones/_new.html.erb
<%= semantic_form_for @milestone, :remote => true do |f| %>
  <%= f.input :name, :hint => 'Milestone name, eg. Basel' %>
  <%= f.input :latitude, :hint => 'Geo position (latitude)', :input_html => {:data => {:geo => 'lat'}} %>
  <%= f.input :longitude, :hint => 'Geo position (longitude)', :input_html => {:data => {:geo => 'lng'}} %>
  <%= f.input :distance, :hint => 'Distance (km) to reach this milestone, eg. 10.5' %>
  <%= f.input :challange_id, :as => :hidden, :value => @challange.id %>

  <%= f.actions do %>
      <%= f.action :submit, :label => 'Ok, add new milestone', :button_html => { :disable_with => 'Wait...' }  %>
  <% end %>
<% end %>

app/views/milestones/edit.js.erb
$('#updates').html("<%= escape_javascript(render(:partial => "edit")) %>").find('#milestone_name').geocomplete({
    details: '#updates',
    detailsAttribute: 'data-geo'
})

app/views/milestones/index.js.erb
$('#updates').empty();
$('#main_content ul.milestones').html("<%= escape_javascript(render(:partial => "index")) %>")

app/views/milestones/new.js.erb
$('#updates').html("<%= escape_javascript(render(:partial => "new")) %>").find('#milestone_name').geocomplete({
    details: "#updates",
    detailsAttribute: "data-geo"
})