config/routes.rb
Fitberry::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  ActiveAdmin.routes(self)

  mount Resque::Server, :at => "/resque"

  resources :activities
  resources :users
  resources :teams
  resources :challanges
  resources :milestones
  resources :blogs
  resources :comments

  devise_scope :user do
    get '/logout' => 'devise/sessions#destroy'
    get '/register' => 'users#register', :as => 'register'
    get '/profile/:id' => 'users#profile', :as => 'profile'

    post '/challanges/:id/activate' => 'challanges#activate', :as => 'activate'
    post '/challanges/:id/rebase' => 'challanges#rebase', :as => 'rebase'

    post '/blogs/:id/publish/' => 'blogs#publish', :as => 'publish'
    post '/blogs/:id/upload/' => 'blogs#upload'
    post '/blogs/preview' => 'blogs#preview'

    post '/comments/:id' => 'comments#create', :as => 'create_comment'
  end

  get '/comments/:id' => 'comments#index', :as => 'comments'
  get '/comments/new/:id' => 'comments#new', :as => 'new_comment'

  get '/history/:chid' => 'activities#index', :as => 'history'
  get '/highscore/:chid' => 'activities#highscore', :as => 'highscore'
  get '/blogs/:chid/:date/:direction' => 'blogs#slide'

  get  '/members' => 'teams#users'

  root :to => 'activities#index'
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :user, :challange, :distance, :steps, :calories_out

  belongs_to :user
  belongs_to :challange

  scope :teamed, lambda { |team_id| joins(:challange).joins(:user).where("users.team_id=?", team_id) }
  scope :teamed_active, lambda { |team_id| teamed(team_id).where("challanges.active=true") }
  scope :active, joins(:challange).where("challanges.active=true").order("distance DESC").readonly(false)
  scope :challanged, lambda{|challange| joins(:challange).where("challanges.id=?", challange.id).order("distance DESC").readonly(false) }

  def self.find_or_initialize_by_user(user)
    if (record = active.where(:user_id => user.id).first).nil?
      record = new(:user => user, :challange => Challange.active.first)
    end
    return record
  end

  def update_from_fitbit(fb_data)
    update_attributes(:calories_out => (fb_data['caloriesOut'] - user.base_calories),
                      :distance => (fb_data['distance'] - user.base_distance).round(2),
                      :steps => (fb_data['steps'] - user.base_steps))
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  # GET /activities
  def index

    # provided by path /history/:id
    id = params[:chid]

    # find the challange either by given id (if history was requested) or by active status
    @challange = (id ? Challange.find(id) : Challange.find_by_active(true)) || Challange.new

    @teams = Team.challanged(@challange)
    @blogs = Blog.recent(@challange)

    @activities = Activity.challanged(@challange).limit(5)
    @milestones = @challange.milestones

    @blog = @blogs.first

    if @blog
      @blog.has_next = false
      @blog.has_prev = @blogs.size > 1
    end

    if @challange.converter
      @challange.money = (@challange.converter * @teams.reduce(0) {|result, obj| result + obj.distance }).round(2)
    end

    respond_to do |format|
      format.html
    end
  end

  def highscore
    challange = Challange.find(params[:chid])
    @activities = Activity.challanged(challange).limit(10)

    respond_to do |format|
      format.js # highscore.js.erb
    end
  end
end

app/views/activities/_blognote.html.erb
<div id="note" xmlns="http://www.w3.org/1999/html">
  <div class="article">
    <div id="content">
      <% if @blog %>
		  <% if @blog.image.exists? %>
			  <%= image_tag @blog.image.url(:original) %>
		  <% end %>
          <h3>
            <%= @blog.title %>
            <span class="date"><%= @blog.published_at.strftime('%m / %d / %Y') %></span>
            <span class="separator">//</span>
            <span class="icon icon-author author"><%= @blog.user.name %></span>
          </h3>
          <p>
            <%= raw @blog.htmlized %>
          </p>
      <% end %>
    </div>
  </div>
  <div class="article-nav">
    <% if @blog; comments = Comment.current(@blog.id).size %>
        <ul class="left">
		  <% if comments > 0 %>
              <li><%= link_to "Comments (#{comments})", comments_path(@blog.id), :class => "icon icon-comments", :remote => true %></li>
		  <% end %>
		  <% if current_user %>
			  <li><%= link_to "Add comment", new_comment_path(@blog.id), :class => "icon icon-write", :remote => true %></li>
		  <% end %>
		</ul>
        <ul class="right">
          <% if @blog.has_prev %>
              <li class="prev icon icon-prev" data-chid="<%= @blog.challange.id %>" data-published="<%= @blog.published_at %>">Previous</li>
          <% end %>
          <% if @blog.has_next %>
              <li class="next icon icon-next" data-chid="<%= @blog.challange.id %>" data-published="<%= @blog.published_at %>">Next</li>
          <% end %>
        </ul>
		<div id="comments"> <!-- placeholder for list of comments --></div>
		<div id="comment"> <!-- placeholder for new comment --> </div>
    <% end %>
  </div>
</div>

app/views/activities/_challange.html.erb
<div class="dash" id="challanges">
  <h5> Challanges </h5>
  <div class="content">
	<% if @challange.id.nil? %>
		<div class="description">
		  <p>
			No challanges defined. <%= link_to 'Please define one', new_admin_challange_path %>.
		  </p>
		</div>
    <% else (Challange.active + Challange.past).each do |challange| current=(challange.id == @challange.id) %>
        <h6>
          <a href="<%= history_url(challange.id) %>" class="icon icon-<%= current ? 'expanded' : 'collapsed' %>">
            <% if challange.finished %> <span class="finished"> Finished. </span> <% end %>
            <%= challange.title %>
          </a>
        </h6>
        <% if current %>
            <div class="description">
              <em>
                <%= raw(challange.htmlized) %>
              </em>
              <hr/>
              <table>
                <% if @challange.deadline %>
                <tr>
                  <td>
					<div class="styled">
					<% if @challange.converter %>
						<div class="money"><%= @challange.money %> PLN<span>Money collected</span></div>
					<% elsif !@challange.finished %>
						<div class="right">Challange ends in:</div>
					<% end %>
					</div>
				  </td>
				  <% if !@challange.finished %>
					  <td><div id="countdown" class="countdown styled" data-timestamp="<%= @challange.deadline %>"></div></td>
				  <% end %>
                </tr>
                <% end %>
                <tr>
                  <td>
                    <strong>Milestones:</strong>
                    <ul>
                      <% challange.milestones.each do |milestone| %>
                          <li><%= milestone.name %>&nbsp;<span>(<%= milestone.distance %>&nbsp;km)</span></li>
                      <% end %>
                    </ul>
                  </td>
                  <td>
                    <strong>Estimated distance:</strong>
                    <ul class="estimate">
                      <li><span class="icon icon-steps steps"><%= challange.distance_steps %></span></li>
                      <li><span class="icon icon-distance distance"><%= challange.distance_km %>&nbsp;km</span></li>
                    </ul>
                  </td>
                </tr>
              </table>
            </div>
        <% end %>
    <% end end %>
  </div>
</div>

app/views/activities/_famehall.html.erb
<h3>Hall of Fame <span> Our <strong>5</strong> most active members:</span></h3>

<table class="menu">
<% @activities.each_with_index do |activity, index| %>
    <% if activity.user.team %>
        <tr>
          <td><a href="#" class="member <%= index > 4 ? 'low' : 'high' %>" data-user="<%= activity.user.id %>"><%= activity.user.name %></a></td>
          <td><span class="team"><%= activity.user.team.name %></span></td>
          <td>from <span class="town"><%= activity.user.town %></span></td>
          <td>distance: <span class="distance"><%= activity.distance %> km</span></td>
        </tr>
    <% end %>
<% end %>
</table>
<% if @activities.size <= 5 && @challange.id %>
    <p>
    <%= link_to raw("See 5 more... &raquo;"), highscore_url(@challange.id), :raw => true, :remote => true %>
    </p>
<% end %>

app/views/activities/_map.html.erb
<div class="dash" id="gmaps">
  <div class="map_container">
	<div id="map">
	  <%= gmaps({}) %>
	</div>
  </div>
</div>

<% content_for :scripts do %>
	<script type="text/javascript">
        var script = '<script type="text/javascript" src="http://google-maps-' +
                'utility-library-v3.googlecode.com/svn/trunk/infobubble/src/infobubble';
        if (document.location.search.indexOf('compiled') !== -1) {
            script += '-compiled';
        }
        script += '.js"><' + '/script>';
        document.write(script);
    </script>
    <script type="text/javascript" charset="utf-8">

        Gmaps.map.callback = function() {
            var directionsService = new google.maps.DirectionsService(),
                directionsDisplay = new google.maps.DirectionsRenderer({
                    markerOptions: {icon: 'http://labs.google.com/ridefinder/images/mm_20_yellow.png'}
                });

            var wpts  = <%= raw((@milestones.map {|m| {:location => "#{m.latitude}, #{m.longitude}"}}).to_json) %>,
                dists = <%= raw((@teams.map {|t| {:distance => t.distance, :name => t.name}}).to_json) %>,
                len   = wpts.length,
                geo   = google.maps.geometry.spherical,
                map   = Gmaps.map.serviceObject;

			// Warszawa is the origin
            wpts.unshift({location: "<%= @challange.origin %>"});

			var request = {
                origin: wpts[0].location,
                destination: wpts[len].location,
                waypoints: wpts.slice(1, len),
                travelMode: google.maps.DirectionsTravelMode.DRIVING
            };

            var infoBubble = new InfoBubble({
                map: map,
                shadowStyle: 1,
                padding: 0,
                backgroundColor: 'rgb(57,57,57)',
                borderRadius: 4,
                borderWidth: 1,
                borderColor: '#2c2c2c',
                disableAutoPan: true,
                hideCloseButton: false,
                arrowStyle: 0,
                backgroundClassName: 'phoney'
            });

            function getTotalDistance(route) {
                for (var total=0, i=0; i<route.legs.length; i++) {
                    total += route.legs[i].distance.value;
                }
                return total;
            }

            function createMarker(position, name, label, color) {
                var marker = new google.maps.Marker({
                    animation: google.maps.Animation.DROP,
                    map: map,
                    icon: 'http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld='+label+'|'+color+'|000000',
                    position: position
                });

                google.maps.event.addListener(marker, 'click', function() {
                    if (infoBubble.isOpen()) {
                        infoBubble.close();
                    }

                    infoBubble.setContent('<div class="phoneytext">'+name+'</div>');
                    infoBubble.open(map, marker);
                })
                return marker;
            }

            function computeMarker(route, distance, total, name, label) {
                var path  = route.overview_path,
                    point = path[0],
                    last  = path[path.length-1],
                    dist  = 0,
                    leg;

                if (distance >= total) {
                    return createMarker(last, name, label, 'FEFEFE');
                }
                for (var p=1; p<path.length; ++p) {
                    leg = Math.round(geo.computeDistanceBetween(point, path[p]));
                    dist += leg;

                    if (dist >= distance) {
                        return createMarker(geo.computeOffset(point, dist-distance, geo.computeHeading(point, path[p])), name, label, 'FE62AA');
                    }
                    point=path[p];
                }
            }

            directionsDisplay.setMap(map);
            directionsService.route(request, function(response, status) {

                if (status == google.maps.DirectionsStatus.OK) {
                    directionsDisplay.setDirections(response);

                    var route = response.routes[0],
                        total = getTotalDistance(route);

                    $.each(dists, function(i, t) {
                        computeMarker(route, t.distance*1000, total, t.name, String.fromCharCode(49+i));
                    })
                }
            });
        }
    </script>
<% end %>

app/views/activities/_teams.html.erb
<div class="dash" id="teams">
  <h5> Teams </h5>
  <div class="content">
    <% if @challange && @challange.milestones.size > 0 %>

        <% @teams.each do |team|
          klass = ""
          team.progress = ((100.0 * team.distance) / @challange.milestones.last.distance).round(1)
          if team.progress >= 100
             team.progress = 100
             klass = "completed"
          end %>

            <div class="team">
              <span class="name"><%= team.name %>&nbsp;&raquo;
                <small>current distance: <%= team.distance %> km</small>
              </span>
              <div class="chart" data-percent="<%= team.progress %>"><%= team.progress %>%</div>
              <div class="tabs">
                <ul>
                  <li class="icon icon-members" data-tab="members" data-id="<%= team.id %>">Members</li>
                  <li class="icon icon-milestones" data-tab="milestones">Milestones</li>
                </ul>
              </div>
              <div class="menu" data-menu="members">
                <!-- placeholder for team members -->
              </div>
              <div class="menu" data-menu="milestones">
                <div class="splitbar">
                  <%
                     prevd = 0
                     milno = nil
                     width ||= (100.0 / (@challange.milestones.size || 1))

                     @challange.milestones.each do |milestone|
                       if team.distance >= milestone.distance
                         milestone.progress = 100
                         prevd = milestone.distance
                       elsif milno.nil?
                         milno, milestone.progress = milestone.number, ((100.0 * (team.distance-prevd)) / (milestone.distance-prevd)).floor
                       else
                         milestone.progress = 0
                       end
                  %>
                      <div class="bar" style="width: <%= width %>%"><div class="ms-<%= milestone.number %>" style="width: <%= milestone.progress %>%"></div></div>
                  <% end %>
                </div>
                <table class="milestones">
                  <tr>
                    <% @challange.milestones.each do |milestone| %>
                        <td width="<%= width %>%">
                          <div class="ms-legend ms-<%= milestone.number %>"></div>
                          <h2> <%= milestone.progress %>% </h2>
                          <small><%= milestone.name %></small>
                        </td>
                    <% end if @challange %>
                  </tr>
                </table>
              </div>
            </div>
        <% end %>
    <% end %>

    <div class="total">
      <%= @teams.size %> teams registered so far...
    </div>
  </div>
</div>

<% content_for :scripts do %>
	<!--[if gte IE 7]><%= javascript_include_tag "excanvas" %><![endif]-->
<% end %>

app/views/activities/highscore.js.erb
$('#wrapper .fame').html("<%= escape_javascript(render :partial => "famehall") %>").find('h3 strong').text("<%= @activities.size %>");

app/views/activities/index.html.erb
<div id="wrapper">
  <!-- blog note -->
  <div class="blog">
	<%= render :partial => 'blognote' %>
  </div>

  <!-- hall of fame -->
  <div class="fame">
    <%= render :partial => 'famehall' %>
  </div>

  <div class="boxes">
	<div class="inner">
	  <div class="left">
		<!-- Challanges -->
		<%= render :partial => 'challange' %>

		<!-- Google map -->
		<%= render :partial => 'map' %>
	  </div>

	  <div class="right">
		<!-- Teams list -->
		<%= render :partial => 'teams' %>
	  </div>
	</div>
  </div>
</div>